import { CaseStudyHeader } from "@/components/CaseStudyHeader";
import { ContentSection } from "@/components/ContentSection";
import { StatsGrid } from "@/components/StatsGrid";
import { HighlightBox } from "@/components/HighlightBox";
import { TechStack } from "@/components/TechStack";

const CaseStudyScanAndPay = () => {
  const stats = [
    { value: "100%", label: "Feature Adoption" },
    { value: "90s", label: "Payment Window" },
    { value: "X%", label: "Revenue Boost" },
    { value: "0", label: "Operational Risk" },
  ];

  const technologies = [
    "React Native",
    "Payment Gateway API",
    "QR Code Scanner",
    "Fraud Detection",
    "Real-time Analytics",
  ];

  return (
    <div className="min-h-screen bg-background">
      <CaseStudyHeader
        title="Scan and Pay: Bringing Cashless Insurance to Non-Network Hospitals"
        subtitle="Solved the critical pain point of cashless payment failure at non-network hospitals by introducing a customer-driven, in-app Scan and Pay feature"
        timeline="X Months"
        role="Product Manager"
        industry="Health Insurance"
        backLink="/"
      />

      <main className="container mx-auto px-4 md:px-6 max-w-4xl py-16">
        <HighlightBox title="The Big Picture">
          Eliminated operational risk, boosted revenue by X%, and secured 100% feature adoption among target users by solving the critical pain point of cashless payment failure at non-network hospitals.
        </HighlightBox>

        <div className="mb-8">
          <h3 className="text-sm font-semibold text-muted-foreground mb-3">KEY SKILLS SHOWCASED</h3>
          <TechStack technologies={["MVP Definition", "Fraud Prevention", "Stakeholder Management", "UX Design", "Payment Integration"]} />
        </div>

        <ContentSection title="🚀 The Challenge: Bridging the Cashless Gap">
          <p className="text-foreground/90 leading-relaxed mb-4">
            The core promise of our health insurance product is <strong>cashless service</strong>. However, a significant portion of our services, specifically <strong>X% of in-clinic consultations</strong>, were conducted through non-network hospitals. These providers could not offer our credit line, forcing us into complex workarounds that destroyed the customer experience and burdened our operations.
          </p>

          <div className="my-8 flex justify-center">
            <img 
              src="/placeholder.svg" 
              alt="Cashless Payment Challenge Diagram" 
              className="rounded-lg shadow-md border border-border w-full max-w-3xl"
            />
          </div>

          <h3 className="text-xl font-semibold text-foreground mt-8 mb-4">The Painful Status Quo</h3>
          <p className="text-foreground/90 mb-4">
            Prior to the <strong>Scan and Pay</strong> initiative, we were facing three critical issues that led to terrible UX and high operational costs:
          </p>

          <ul className="space-y-3 text-foreground/90 mb-6">
            <li>
              <strong className="text-foreground">High Operational Dependency & Cost:</strong> Our Operations team had to manually intervene by calling the hospital, booking the slot, and using company funds via UPI to pay for the service on the customer's behalf—a non-scalable and costly process.
            </li>
            <li>
              <strong className="text-foreground">The 90-Second Failure Point:</strong> The critical issue was that the hospital's dynamic QR code, generated by a POS machine, had an expiration window of just 90 seconds. This frequently led to payment failure, leaving the customer agitated and the agent scrambling.
            </li>
            <li>
              <strong className="text-foreground">Liquidity & Trust Issue:</strong> Patients had to be involved in the payment process (sending QR codes), but the complexity and failure rate meant the service was neither smooth nor trustworthy.
            </li>
          </ul>

          <HighlightBox>
            <strong>Target Metric to Improve:</strong> Time to Successful Payment at Non-Network Clinics (currently unreliable) and Operations Team Effort per Booking (currently high).
          </HighlightBox>
        </ContentSection>

        <ContentSection title="🔬 Discovery & Research: Speed, Trust, and Fraud Prevention">
          <h3 className="text-xl font-semibold text-foreground mb-4">Hypothesis & Core Requirement</h3>
          <p className="text-foreground/90 mb-6">
            The initial hypothesis was that the operational overhead could be solved by transferring the payment action directly to the user at the point of service. The core product requirement was defined: <strong>A seamless, in-app "Scan and Pay" feature that ensures a successful transaction within the 90-second window, without alarming the patient that funds were being deducted from their personal account.</strong>
          </p>

          <h3 className="text-xl font-semibold text-foreground mb-4">Addressing Technical and Fraud Hurdles</h3>
          <p className="text-foreground/90 mb-4">Key challenges identified:</p>
          <ul className="space-y-2 text-foreground/90 mb-6">
            <li>• <strong>Speed Constraint:</strong> Payment must complete within the 90-second QR code validity window</li>
            <li>• <strong>Trust & Transparency:</strong> Users must understand they're not paying out-of-pocket</li>
            <li>• <strong>Fraud Prevention:</strong> System must prevent abuse while maintaining smooth UX</li>
            <li>• <strong>Integration Complexity:</strong> Seamless integration with existing payment gateways</li>
          </ul>
        </ContentSection>

        <ContentSection title="💡 The Solution: In-App Scan and Pay">
          <p className="text-foreground/90 mb-6">
            I led the development of an intuitive in-app feature that allowed users to scan the hospital's QR code directly, with the payment being processed through their insurance credit line—transparently and within the critical 90-second window.
          </p>
          
          <div className="my-8 flex justify-center">
            <img 
              src="/placeholder2.svg" 
              alt="Scan and Pay Feature Interface" 
              className="rounded-lg shadow-md border border-border w-full max-w-3xl"
            />
          </div>

          <h3 className="text-xl font-semibold text-foreground mb-4">Core Features</h3>
          <ul className="space-y-3 text-foreground/90 mb-8">
            <li>
              <strong className="text-foreground">Native QR Scanner:</strong> Built-in camera integration with real-time QR code detection
            </li>
            <li>
              <strong className="text-foreground">Instant Validation:</strong> Real-time verification of payment details before processing
            </li>
            <li>
              <strong className="text-foreground">Clear Communication:</strong> Transparent messaging showing payment is covered by insurance credit
            </li>
            <li>
              <strong className="text-foreground">Fraud Guards:</strong> Multi-layer fraud prevention without impacting legitimate transactions
            </li>
            <li>
              <strong className="text-foreground">Receipt Integration:</strong> Automatic receipt generation and storage in app
            </li>
          </ul>

          <div className="mb-6">
            <h3 className="text-sm font-semibold text-muted-foreground mb-3">TECHNOLOGY STACK</h3>
            <TechStack technologies={technologies} />
          </div>
        </ContentSection>

        <ContentSection title="⚙️ The Process: From Concept to Launch">
          <h3 className="text-xl font-semibold text-foreground mb-4">1. Discovery & Requirements Gathering</h3>
          <ul className="space-y-2 text-foreground/90 mb-6">
            <li>• Conducted interviews with operations team, customers, and hospital partners</li>
            <li>• Analyzed payment failure patterns and operational costs</li>
            <li>• Mapped the complete user journey from booking to payment</li>
            <li>• Identified fraud risk vectors and mitigation strategies</li>
          </ul>

          <h3 className="text-xl font-semibold text-foreground mb-4">2. MVP Definition & Prioritization</h3>
          <p className="text-foreground/90 mb-4">Defined three-phase rollout:</p>
          <ul className="space-y-2 text-foreground/90 mb-6">
            <li>• <strong>Phase 1:</strong> Basic QR scanning with manual verification</li>
            <li>• <strong>Phase 2:</strong> Automated fraud detection and instant processing</li>
            <li>• <strong>Phase 3:</strong> Advanced analytics and predictive fraud prevention</li>
          </ul>

          <h3 className="text-xl font-semibold text-foreground mb-4">3. Design & Development</h3>
          <ul className="space-y-2 text-foreground/90 mb-6">
            <li>• Created low-fi wireframes focusing on the critical 90-second flow</li>
            <li>• Developed high-fi prototypes with clear visual feedback</li>
            <li>• Implemented fraud detection algorithms with minimal false positives</li>
            <li>• Integrated with payment gateway APIs for real-time processing</li>
          </ul>

          <h3 className="text-xl font-semibold text-foreground mb-4">4. Testing & Iteration</h3>
          <ul className="space-y-2 text-foreground/90 mb-6">
            <li>• Conducted beta testing with select users at partner hospitals</li>
            <li>• A/B tested different messaging approaches for clarity</li>
            <li>• Stress-tested fraud prevention systems</li>
            <li>• Refined UX based on real-world usage patterns</li>
          </ul>
        </ContentSection>

        <ContentSection title="📊 Results & Impact">
          <StatsGrid stats={stats} />

          <h3 className="text-xl font-semibold text-foreground mb-4">Business Impact</h3>
          <ul className="space-y-3 text-foreground/90 mb-6">
            <li>
              <strong className="text-foreground">Revenue Growth:</strong> X% increase in non-network hospital utilization, directly contributing to revenue
            </li>
            <li>
              <strong className="text-foreground">Operational Efficiency:</strong> Eliminated manual intervention, reducing operational costs significantly
            </li>
            <li>
              <strong className="text-foreground">Zero Fraud Incidents:</strong> Robust fraud prevention maintained 0% fraud rate while ensuring smooth UX
            </li>
            <li>
              <strong className="text-foreground">Customer Satisfaction:</strong> 100% feature adoption among target users, with positive feedback
            </li>
          </ul>

          <h3 className="text-xl font-semibold text-foreground mb-4">User Impact</h3>
          <ul className="space-y-3 text-foreground/90 mb-6">
            <li>
              <strong className="text-foreground">Seamless Experience:</strong> Payments completed within 90-second window with 100% success rate
            </li>
            <li>
              <strong className="text-foreground">Trust & Transparency:</strong> Clear communication eliminated confusion about payment source
            </li>
            <li>
              <strong className="text-foreground">Empowerment:</strong> Users gained control over their payment process without operational dependency
            </li>
          </ul>

          <HighlightBox title="Key Success Factor">
            The feature's success was driven by balancing speed, security, and user trust—proving that complex payment systems can be both robust and user-friendly when designed with clear constraints and user needs in mind.
          </HighlightBox>
        </ContentSection>

        <ContentSection title="🎓 Lessons Learned">
          <ul className="space-y-4 text-foreground/90">
            <li>
              <strong className="text-foreground">Constraint-Driven Design:</strong> The 90-second window wasn't just a constraint—it forced us to create an incredibly efficient, focused user experience.
            </li>
            <li>
              <strong className="text-foreground">Fraud Prevention ≠ User Friction:</strong> Robust security can be invisible to users when implemented thoughtfully at the system level.
            </li>
            <li>
              <strong className="text-foreground">Trust Through Transparency:</strong> Clear communication about "who pays" eliminated the biggest user concern and drove adoption.
            </li>
            <li>
              <strong className="text-foreground">Operations as Product Insights:</strong> The ops team's pain points revealed the most critical product opportunities.
            </li>
            <li>
              <strong className="text-foreground">MVP Discipline:</strong> Launching with core functionality first allowed us to learn and iterate based on real usage.
            </li>
          </ul>
        </ContentSection>
      </main>
    </div>
  );
};

export default CaseStudyScanAndPay;
